[package]
name = "TOTP-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
base32 = "0.5.1"
clap = "2"
hmac = "0.12.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
sha1 = "0.10.6"
sha2 = "0.10.8"
